### ISSUE TITLE
Analog range

### ISSUE THREAD

**Issue by Alkovalski** [Davidobot/BetterJoy#524]
**Describe the bug**

**Expected behavior**

**Controller (please complete the following information):**
 - Type: [e.g. Pro/Split Joycons]
 - Connection: [e.g. USB/BT]

**Comment by shukenmg** [comment]
Did you turn on the Non Original Controller option?

**Comment by Alkovalski** [comment]
Yeah, without Non original enabled I coudn't even use my controller on my PC

**Comment by shukenmg** [comment]
@Alkovalski What controller are you using?

**Comment by Alkovalski** [comment]
An Xenoblade Pro Controller, its not original, but it works like how an original should on my switch, all analog sticks are good when I test them

**Comment by shukenmg** [comment]
What happens when you disable the original controller setting?

**Comment by Alkovalski** [comment]
It just dont works
Like, the controller will do absolutely nothing, after applying the settings with "non original controller" enabled, it works, but with analog stick getting about 50% the normal range (if I set the range on Cemu to around 148-150% it feels like intended range)

**Comment by shukenmg** [comment]
Ok, I made a test build for you to test, you can turn on the Non-Controller Setting, it should fix the analog problem, if not let me know.
[TestV1.zip](https://github.com/Davidobot/BetterJoy/files/5244060/TestV1.zip)

**Comment by Alkovalski** [comment]
![nice](https://user-images.githubusercontent.com/57607487/93584588-e2d31780-f97b-11ea-8cf3-2206878bf966.png)
I think its fixed now!
Both controllers are giving almost the same value
Thanks man!
What did you change?

**Comment by shukenmg** [comment]
I changed the code where it set stick calibration, depending on the Non-Original Controller option.

**Comment by monsterg2** [comment]
I'm still having an issue where the range is limited to 85% constantly. It's happening to both analog sticks when I move it West, North, and East. However, South goes full 100%. I used Test v1, same issue. It's prevalent in games where 100% on the axes toggles running movement.

**Comment by shukenmg** [comment]
What controller are you using?
